// Since: cosmos-sdk 0.43

// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/feegrant/v1beta1/genesis.proto (package cosmos.feegrant.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Grant } from "./feegrant_pb";
import { file_cosmos_feegrant_v1beta1_feegrant } from "./feegrant_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/feegrant/v1beta1/genesis.proto.
 */
export const file_cosmos_feegrant_v1beta1_genesis: GenFile = /*@__PURE__*/
  fileDesc("CiVjb3Ntb3MvZmVlZ3JhbnQvdjFiZXRhMS9nZW5lc2lzLnByb3RvEhdjb3Ntb3MuZmVlZ3JhbnQudjFiZXRhMSJNCgxHZW5lc2lzU3RhdGUSPQoKYWxsb3dhbmNlcxgBIAMoCzIeLmNvc21vcy5mZWVncmFudC52MWJldGExLkdyYW50QgnI3h8AqOewKgFCGVoXY29zbW9zc2RrLmlvL3gvZmVlZ3JhbnRiBnByb3RvMw", [file_gogoproto_gogo, file_cosmos_feegrant_v1beta1_feegrant, file_amino_amino]);

/**
 * GenesisState contains a set of fee allowances, persisted from the store
 *
 * @generated from message cosmos.feegrant.v1beta1.GenesisState
 */
export type GenesisState = Message<"cosmos.feegrant.v1beta1.GenesisState"> & {
  /**
   * @generated from field: repeated cosmos.feegrant.v1beta1.Grant allowances = 1;
   */
  allowances: Grant[];
};

/**
 * Describes the message cosmos.feegrant.v1beta1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_cosmos_feegrant_v1beta1_genesis, 0);

