// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/store/internal/kv/v1beta1/kv.proto (package cosmos.store.internal.kv.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/store/internal/kv/v1beta1/kv.proto.
 */
export const file_cosmos_store_internal_kv_v1beta1_kv: GenFile = /*@__PURE__*/
  fileDesc("Ciljb3Ntb3Mvc3RvcmUvaW50ZXJuYWwva3YvdjFiZXRhMS9rdi5wcm90bxIgY29zbW9zLnN0b3JlLmludGVybmFsLmt2LnYxYmV0YTEiRAoFUGFpcnMSOwoFcGFpcnMYASADKAsyJi5jb3Ntb3Muc3RvcmUuaW50ZXJuYWwua3YudjFiZXRhMS5QYWlyQgTI3h8AIiIKBFBhaXISCwoDa2V5GAEgASgMEg0KBXZhbHVlGAIgASgMQiBaHmNvc21vc3Nkay5pby9zdG9yZS9pbnRlcm5hbC9rdmIGcHJvdG8z", [file_gogoproto_gogo]);

/**
 * Pairs defines a repeated slice of Pair objects.
 *
 * @generated from message cosmos.store.internal.kv.v1beta1.Pairs
 */
export type Pairs = Message<"cosmos.store.internal.kv.v1beta1.Pairs"> & {
  /**
   * @generated from field: repeated cosmos.store.internal.kv.v1beta1.Pair pairs = 1;
   */
  pairs: Pair[];
};

/**
 * Describes the message cosmos.store.internal.kv.v1beta1.Pairs.
 * Use `create(PairsSchema)` to create a new message.
 */
export const PairsSchema: GenMessage<Pairs> = /*@__PURE__*/
  messageDesc(file_cosmos_store_internal_kv_v1beta1_kv, 0);

/**
 * Pair defines a key/value bytes tuple.
 *
 * @generated from message cosmos.store.internal.kv.v1beta1.Pair
 */
export type Pair = Message<"cosmos.store.internal.kv.v1beta1.Pair"> & {
  /**
   * @generated from field: bytes key = 1;
   */
  key: Uint8Array;

  /**
   * @generated from field: bytes value = 2;
   */
  value: Uint8Array;
};

/**
 * Describes the message cosmos.store.internal.kv.v1beta1.Pair.
 * Use `create(PairSchema)` to create a new message.
 */
export const PairSchema: GenMessage<Pair> = /*@__PURE__*/
  messageDesc(file_cosmos_store_internal_kv_v1beta1_kv, 1);

