// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/orm/module/v1alpha1/module.proto (package cosmos.orm.module.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_app_v1alpha1_module } from "../../../app/v1alpha1/module_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/orm/module/v1alpha1/module.proto.
 */
export const file_cosmos_orm_module_v1alpha1_module: GenFile = /*@__PURE__*/
  fileDesc("Cidjb3Ntb3Mvb3JtL21vZHVsZS92MWFscGhhMS9tb2R1bGUucHJvdG8SGmNvc21vcy5vcm0ubW9kdWxlLnYxYWxwaGExIiIKBk1vZHVsZToYusCW2gESChBjb3Ntb3NzZGsuaW8vb3JtYgZwcm90bzM", [file_cosmos_app_v1alpha1_module]);

/**
 * Module defines the ORM module which adds providers to the app container for
 * ORM ModuleDB's and in the future will automatically register query
 * services for modules that use the ORM.
 *
 * @generated from message cosmos.orm.module.v1alpha1.Module
 */
export type Module = Message<"cosmos.orm.module.v1alpha1.Module"> & {
};

/**
 * Describes the message cosmos.orm.module.v1alpha1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_cosmos_orm_module_v1alpha1_module, 0);

