// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/asset/nft/v1/authz.proto (package coreum.asset.nft.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../../amino/amino_pb";
import { file_cosmos_proto_cosmos } from "../../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/asset/nft/v1/authz.proto.
 */
export const file_coreum_asset_nft_v1_authz: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb3JldW0vYXNzZXQvbmZ0L3YxL2F1dGh6LnByb3RvEhNjb3JldW0uYXNzZXQubmZ0LnYxIp0BChFTZW5kQXV0aG9yaXphdGlvbhI7CgRuZnRzGAEgAygLMiIuY29yZXVtLmFzc2V0Lm5mdC52MS5ORlRJZGVudGlmaWVyQgnI3h8AqOewKgE6S8q0LSJjb3Ntb3MuYXV0aHoudjFiZXRhMS5BdXRob3JpemF0aW9uiuewKiBjb3Ntb3Mtc2RrL25mdC9TZW5kQXV0aG9yaXphdGlvbiItCg1ORlRJZGVudGlmaWVyEhAKCGNsYXNzX2lkGAEgASgJEgoKAmlkGAIgASgJQjlaN2dpdGh1Yi5jb20vQ29yZXVtRm91bmRhdGlvbi9jb3JldW0vdjQveC9hc3NldC9uZnQvdHlwZXNiBnByb3RvMw", [file_amino_amino, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * SendAuthorization allows the grantee to send specific NFTs from the granter's account.
 *
 * @generated from message coreum.asset.nft.v1.SendAuthorization
 */
export type SendAuthorization = Message<"coreum.asset.nft.v1.SendAuthorization"> & {
  /**
   * @generated from field: repeated coreum.asset.nft.v1.NFTIdentifier nfts = 1;
   */
  nfts: NFTIdentifier[];
};

/**
 * Describes the message coreum.asset.nft.v1.SendAuthorization.
 * Use `create(SendAuthorizationSchema)` to create a new message.
 */
export const SendAuthorizationSchema: GenMessage<SendAuthorization> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_authz, 0);

/**
 * @generated from message coreum.asset.nft.v1.NFTIdentifier
 */
export type NFTIdentifier = Message<"coreum.asset.nft.v1.NFTIdentifier"> & {
  /**
   * class_id defines the unique identifier of the nft classification, similar to the contract address of ERC721
   *
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * id defines the unique identification of nft
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message coreum.asset.nft.v1.NFTIdentifier.
 * Use `create(NFTIdentifierSchema)` to create a new message.
 */
export const NFTIdentifierSchema: GenMessage<NFTIdentifier> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_authz, 1);

