// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/asset/nft/v1/event.proto (package coreum.asset.nft.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ClassFeature } from "./nft_pb";
import { file_coreum_asset_nft_v1_nft } from "./nft_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/asset/nft/v1/event.proto.
 */
export const file_coreum_asset_nft_v1_event: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb3JldW0vYXNzZXQvbmZ0L3YxL2V2ZW50LnByb3RvEhNjb3JldW0uYXNzZXQubmZ0LnYxIo4CChBFdmVudENsYXNzSXNzdWVkEhIKAmlkGAEgASgJQgbi3h8CSUQSDgoGaXNzdWVyGAIgASgJEg4KBnN5bWJvbBgDIAEoCRIMCgRuYW1lGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJEhQKA3VyaRgGIAEoCUIH4t4fA1VSSRIdCgh1cmlfaGFzaBgHIAEoCUIL4t4fB1VSSUhhc2gSMwoIZmVhdHVyZXMYCCADKA4yIS5jb3JldW0uYXNzZXQubmZ0LnYxLkNsYXNzRmVhdHVyZRI5Cgxyb3lhbHR5X3JhdGUYCSABKAlCI8jeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVjIjoKC0V2ZW50RnJvemVuEhAKCGNsYXNzX2lkGAEgASgJEgoKAmlkGAIgASgJEg0KBW93bmVyGAMgASgJIjwKDUV2ZW50VW5mcm96ZW4SEAoIY2xhc3NfaWQYASABKAkSCgoCaWQYAiABKAkSDQoFb3duZXIYAyABKAkiNQoQRXZlbnRDbGFzc0Zyb3plbhIQCghjbGFzc19pZBgBIAEoCRIPCgdhY2NvdW50GAMgASgJIjcKEkV2ZW50Q2xhc3NVbmZyb3plbhIQCghjbGFzc19pZBgBIAEoCRIPCgdhY2NvdW50GAMgASgJIkYKFUV2ZW50QWRkZWRUb1doaXRlbGlzdBIQCghjbGFzc19pZBgBIAEoCRIKCgJpZBgCIAEoCRIPCgdhY2NvdW50GAMgASgJIkoKGUV2ZW50UmVtb3ZlZEZyb21XaGl0ZWxpc3QSEAoIY2xhc3NfaWQYASABKAkSCgoCaWQYAiABKAkSDwoHYWNjb3VudBgDIAEoCSI/ChpFdmVudEFkZGVkVG9DbGFzc1doaXRlbGlzdBIQCghjbGFzc19pZBgBIAEoCRIPCgdhY2NvdW50GAIgASgJIkMKHkV2ZW50UmVtb3ZlZEZyb21DbGFzc1doaXRlbGlzdBIQCghjbGFzc19pZBgBIAEoCRIPCgdhY2NvdW50GAIgASgJQjlaN2dpdGh1Yi5jb20vQ29yZXVtRm91bmRhdGlvbi9jb3JldW0vdjQveC9hc3NldC9uZnQvdHlwZXNiBnByb3RvMw", [file_coreum_asset_nft_v1_nft, file_gogoproto_gogo]);

/**
 * EventClassIssued is emitted on MsgIssueClass.
 *
 * @generated from message coreum.asset.nft.v1.EventClassIssued
 */
export type EventClassIssued = Message<"coreum.asset.nft.v1.EventClassIssued"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string issuer = 2;
   */
  issuer: string;

  /**
   * @generated from field: string symbol = 3;
   */
  symbol: string;

  /**
   * @generated from field: string name = 4;
   */
  name: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: string uri = 6;
   */
  uri: string;

  /**
   * @generated from field: string uri_hash = 7;
   */
  uriHash: string;

  /**
   * @generated from field: repeated coreum.asset.nft.v1.ClassFeature features = 8;
   */
  features: ClassFeature[];

  /**
   * @generated from field: string royalty_rate = 9;
   */
  royaltyRate: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventClassIssued.
 * Use `create(EventClassIssuedSchema)` to create a new message.
 */
export const EventClassIssuedSchema: GenMessage<EventClassIssued> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 0);

/**
 * @generated from message coreum.asset.nft.v1.EventFrozen
 */
export type EventFrozen = Message<"coreum.asset.nft.v1.EventFrozen"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string owner = 3;
   */
  owner: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventFrozen.
 * Use `create(EventFrozenSchema)` to create a new message.
 */
export const EventFrozenSchema: GenMessage<EventFrozen> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 1);

/**
 * @generated from message coreum.asset.nft.v1.EventUnfrozen
 */
export type EventUnfrozen = Message<"coreum.asset.nft.v1.EventUnfrozen"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string owner = 3;
   */
  owner: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventUnfrozen.
 * Use `create(EventUnfrozenSchema)` to create a new message.
 */
export const EventUnfrozenSchema: GenMessage<EventUnfrozen> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 2);

/**
 * @generated from message coreum.asset.nft.v1.EventClassFrozen
 */
export type EventClassFrozen = Message<"coreum.asset.nft.v1.EventClassFrozen"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string account = 3;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventClassFrozen.
 * Use `create(EventClassFrozenSchema)` to create a new message.
 */
export const EventClassFrozenSchema: GenMessage<EventClassFrozen> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 3);

/**
 * @generated from message coreum.asset.nft.v1.EventClassUnfrozen
 */
export type EventClassUnfrozen = Message<"coreum.asset.nft.v1.EventClassUnfrozen"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string account = 3;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventClassUnfrozen.
 * Use `create(EventClassUnfrozenSchema)` to create a new message.
 */
export const EventClassUnfrozenSchema: GenMessage<EventClassUnfrozen> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 4);

/**
 * @generated from message coreum.asset.nft.v1.EventAddedToWhitelist
 */
export type EventAddedToWhitelist = Message<"coreum.asset.nft.v1.EventAddedToWhitelist"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string account = 3;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventAddedToWhitelist.
 * Use `create(EventAddedToWhitelistSchema)` to create a new message.
 */
export const EventAddedToWhitelistSchema: GenMessage<EventAddedToWhitelist> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 5);

/**
 * @generated from message coreum.asset.nft.v1.EventRemovedFromWhitelist
 */
export type EventRemovedFromWhitelist = Message<"coreum.asset.nft.v1.EventRemovedFromWhitelist"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string account = 3;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventRemovedFromWhitelist.
 * Use `create(EventRemovedFromWhitelistSchema)` to create a new message.
 */
export const EventRemovedFromWhitelistSchema: GenMessage<EventRemovedFromWhitelist> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 6);

/**
 * @generated from message coreum.asset.nft.v1.EventAddedToClassWhitelist
 */
export type EventAddedToClassWhitelist = Message<"coreum.asset.nft.v1.EventAddedToClassWhitelist"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string account = 2;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventAddedToClassWhitelist.
 * Use `create(EventAddedToClassWhitelistSchema)` to create a new message.
 */
export const EventAddedToClassWhitelistSchema: GenMessage<EventAddedToClassWhitelist> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 7);

/**
 * @generated from message coreum.asset.nft.v1.EventRemovedFromClassWhitelist
 */
export type EventRemovedFromClassWhitelist = Message<"coreum.asset.nft.v1.EventRemovedFromClassWhitelist"> & {
  /**
   * @generated from field: string class_id = 1;
   */
  classId: string;

  /**
   * @generated from field: string account = 2;
   */
  account: string;
};

/**
 * Describes the message coreum.asset.nft.v1.EventRemovedFromClassWhitelist.
 * Use `create(EventRemovedFromClassWhitelistSchema)` to create a new message.
 */
export const EventRemovedFromClassWhitelistSchema: GenMessage<EventRemovedFromClassWhitelist> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_event, 8);

