// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/asset/nft/v1/nft.proto (package coreum.asset.nft.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Any } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/asset/nft/v1/nft.proto.
 */
export const file_coreum_asset_nft_v1_nft: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb3JldW0vYXNzZXQvbmZ0L3YxL25mdC5wcm90bxITY29yZXVtLmFzc2V0Lm5mdC52MSKlAQoPQ2xhc3NEZWZpbml0aW9uEhIKAmlkGAEgASgJQgbi3h8CSUQSDgoGaXNzdWVyGAIgASgJEjMKCGZlYXR1cmVzGAMgAygOMiEuY29yZXVtLmFzc2V0Lm5mdC52MS5DbGFzc0ZlYXR1cmUSOQoMcm95YWx0eV9yYXRlGAQgASgJQiPI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlYyKfAgoFQ2xhc3MSCgoCaWQYASABKAkSDgoGaXNzdWVyGAIgASgJEgwKBG5hbWUYAyABKAkSDgoGc3ltYm9sGAQgASgJEhMKC2Rlc2NyaXB0aW9uGAUgASgJEhQKA3VyaRgGIAEoCUIH4t4fA1VSSRIdCgh1cmlfaGFzaBgHIAEoCUIL4t4fB1VSSUhhc2gSIgoEZGF0YRgIIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5BbnkSMwoIZmVhdHVyZXMYCSADKA4yIS5jb3JldW0uYXNzZXQubmZ0LnYxLkNsYXNzRmVhdHVyZRI5Cgxyb3lhbHR5X3JhdGUYCiABKAlCI8jeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVjKl8KDENsYXNzRmVhdHVyZRILCgdidXJuaW5nEAASDAoIZnJlZXppbmcQARIQCgx3aGl0ZWxpc3RpbmcQAhITCg9kaXNhYmxlX3NlbmRpbmcQAxINCglzb3VsYm91bmQQBEI5WjdnaXRodWIuY29tL0NvcmV1bUZvdW5kYXRpb24vY29yZXVtL3Y0L3gvYXNzZXQvbmZ0L3R5cGVzYgZwcm90bzM", [file_gogoproto_gogo, file_google_protobuf_any]);

/**
 * ClassDefinition defines the non-fungible token class settings to store.
 *
 * @generated from message coreum.asset.nft.v1.ClassDefinition
 */
export type ClassDefinition = Message<"coreum.asset.nft.v1.ClassDefinition"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string issuer = 2;
   */
  issuer: string;

  /**
   * @generated from field: repeated coreum.asset.nft.v1.ClassFeature features = 3;
   */
  features: ClassFeature[];

  /**
   * royalty_rate is a number between 0 and 1,which will be used in coreum native Dex.
   * whenever an NFT this class is traded on the Dex, the traded amount will be multiplied by this value
   * that will be transferred to the issuer of the NFT.
   *
   * @generated from field: string royalty_rate = 4;
   */
  royaltyRate: string;
};

/**
 * Describes the message coreum.asset.nft.v1.ClassDefinition.
 * Use `create(ClassDefinitionSchema)` to create a new message.
 */
export const ClassDefinitionSchema: GenMessage<ClassDefinition> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_nft, 0);

/**
 * Class is a full representation of the non-fungible token class.
 *
 * @generated from message coreum.asset.nft.v1.Class
 */
export type Class = Message<"coreum.asset.nft.v1.Class"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string issuer = 2;
   */
  issuer: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string symbol = 4;
   */
  symbol: string;

  /**
   * @generated from field: string description = 5;
   */
  description: string;

  /**
   * @generated from field: string uri = 6;
   */
  uri: string;

  /**
   * @generated from field: string uri_hash = 7;
   */
  uriHash: string;

  /**
   * @generated from field: google.protobuf.Any data = 8;
   */
  data?: Any;

  /**
   * @generated from field: repeated coreum.asset.nft.v1.ClassFeature features = 9;
   */
  features: ClassFeature[];

  /**
   * royalty_rate is a number between 0 and 1,which will be used in coreum native Dex.
   * whenever an NFT this class is traded on the Dex, the traded amount will be multiplied by this value
   * that will be transferred to the issuer of the NFT.
   *
   * @generated from field: string royalty_rate = 10;
   */
  royaltyRate: string;
};

/**
 * Describes the message coreum.asset.nft.v1.Class.
 * Use `create(ClassSchema)` to create a new message.
 */
export const ClassSchema: GenMessage<Class> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_nft, 1);

/**
 * ClassFeature defines possible features of non-fungible token class.
 *
 * @generated from enum coreum.asset.nft.v1.ClassFeature
 */
export enum ClassFeature {
  /**
   * @generated from enum value: burning = 0;
   */
  burning = 0,

  /**
   * @generated from enum value: freezing = 1;
   */
  freezing = 1,

  /**
   * @generated from enum value: whitelisting = 2;
   */
  whitelisting = 2,

  /**
   * @generated from enum value: disable_sending = 3;
   */
  disable_sending = 3,

  /**
   * @generated from enum value: soulbound = 4;
   */
  soulbound = 4,
}

/**
 * Describes the enum coreum.asset.nft.v1.ClassFeature.
 */
export const ClassFeatureSchema: GenEnum<ClassFeature> = /*@__PURE__*/
  enumDesc(file_coreum_asset_nft_v1_nft, 0);

