// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/asset/nft/v1/params.proto (package coreum.asset.nft.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/asset/nft/v1/params.proto.
 */
export const file_coreum_asset_nft_v1_params: GenFile = /*@__PURE__*/
  fileDesc("CiBjb3JldW0vYXNzZXQvbmZ0L3YxL3BhcmFtcy5wcm90bxITY29yZXVtLmFzc2V0Lm5mdC52MSJOCgZQYXJhbXMSRAoIbWludF9mZWUYASABKAsyGS5jb3Ntb3MuYmFzZS52MWJldGExLkNvaW5CF8jeHwDy3h8PeWFtbDoibWludF9mZWUiQjlaN2dpdGh1Yi5jb20vQ29yZXVtRm91bmRhdGlvbi9jb3JldW0vdjQveC9hc3NldC9uZnQvdHlwZXNiBnByb3RvMw", [file_cosmos_base_v1beta1_coin, file_gogoproto_gogo]);

/**
 * Params store gov manageable parameters.
 *
 * @generated from message coreum.asset.nft.v1.Params
 */
export type Params = Message<"coreum.asset.nft.v1.Params"> & {
  /**
   * mint_fee is the fee burnt each time new NFT is minted
   *
   * @generated from field: cosmos.base.v1beta1.Coin mint_fee = 1;
   */
  mintFee?: Coin;
};

/**
 * Describes the message coreum.asset.nft.v1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_coreum_asset_nft_v1_params, 0);

