// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/dex/v1/genesis.proto (package coreum.dex.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Params } from "./params_pb";
import { file_coreum_dex_v1_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/dex/v1/genesis.proto.
 */
export const file_coreum_dex_v1_genesis: GenFile = /*@__PURE__*/
  fileDesc("Chtjb3JldW0vZGV4L3YxL2dlbmVzaXMucHJvdG8SDWNvcmV1bS5kZXgudjEiOwoMR2VuZXNpc1N0YXRlEisKBnBhcmFtcxgBIAEoCzIVLmNvcmV1bS5kZXgudjEuUGFyYW1zQgTI3h8AQjNaMWdpdGh1Yi5jb20vQ29yZXVtRm91bmRhdGlvbi9jb3JldW0vdjQveC9kZXgvdHlwZXNiBnByb3RvMw", [file_coreum_dex_v1_params, file_gogoproto_gogo]);

/**
 * GenesisState defines the module genesis state.
 *
 * @generated from message coreum.dex.v1.GenesisState
 */
export type GenesisState = Message<"coreum.dex.v1.GenesisState"> & {
  /**
   * params defines all the parameters of the module.
   *
   * @generated from field: coreum.dex.v1.Params params = 1;
   */
  params?: Params;
};

/**
 * Describes the message coreum.dex.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_genesis, 0);

