// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/dex/v1/order.proto (package coreum.dex.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/dex/v1/order.proto.
 */
export const file_coreum_dex_v1_order: GenFile = /*@__PURE__*/
  fileDesc("Chljb3JldW0vZGV4L3YxL29yZGVyLnByb3RvEg1jb3JldW0uZGV4LnYxIuACCgVPcmRlchIPCgdjcmVhdG9yGAEgASgJEiYKBHR5cGUYAiABKA4yGC5jb3JldW0uZGV4LnYxLk9yZGVyVHlwZRISCgJpZBgDIAEoCUIG4t4fAklEEhIKCmJhc2VfZGVub20YBCABKAkSEwoLcXVvdGVfZGVub20YBSABKAkSGAoFcHJpY2UYBiABKAlCCdreHwVQcmljZRIvCghxdWFudGl0eRgHIAEoCUIdyN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnQSIQoEc2lkZRgIIAEoDjITLmNvcmV1bS5kZXgudjEuU2lkZRI5ChJyZW1haW5pbmdfcXVhbnRpdHkYCSABKAlCHcjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW50EjgKEXJlbWFpbmluZ19iYWxhbmNlGAogASgJQh3I3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludCKlAQoJT3JkZXJEYXRhEiYKDW9yZGVyX2Jvb2tfaWQYASABKA1CD+LeHwtPcmRlckJvb2tJRBIcCgVwcmljZRgCIAEoCUINyN4fANreHwVQcmljZRIvCghxdWFudGl0eRgDIAEoCUIdyN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnQSIQoEc2lkZRgEIAEoDjITLmNvcmV1bS5kZXgudjEuU2lkZSI4Cg1PcmRlckJvb2tEYXRhEhIKCmJhc2VfZGVub20YASABKAkSEwoLcXVvdGVfZGVub20YAiABKAkiuQIKD09yZGVyQm9va1JlY29yZBImCg1vcmRlcl9ib29rX2lkGAEgASgNQg/i3h8LT3JkZXJCb29rSUQSIQoEc2lkZRgCIAEoDjITLmNvcmV1bS5kZXgudjEuU2lkZRIcCgVwcmljZRgDIAEoCUINyN4fANreHwVQcmljZRIRCglvcmRlcl9zZXEYBCABKAQSHQoIb3JkZXJfaWQYBSABKAlCC+LeHwdPcmRlcklEEhYKDmFjY291bnRfbnVtYmVyGAYgASgEEjkKEnJlbWFpbmluZ19xdWFudGl0eRgHIAEoCUIdyN4fANreHxVjb3Ntb3NzZGsuaW8vbWF0aC5JbnQSOAoRcmVtYWluaW5nX2JhbGFuY2UYCCABKAlCHcjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW50IsEBChNPcmRlckJvb2tSZWNvcmREYXRhEh0KCG9yZGVyX2lkGAEgASgJQgvi3h8HT3JkZXJJRBIWCg5hY2NvdW50X251bWJlchgCIAEoBBI5ChJyZW1haW5pbmdfcXVhbnRpdHkYAyABKAlCHcjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW50EjgKEXJlbWFpbmluZ19iYWxhbmNlGAQgASgJQh3I3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludCo/CgRTaWRlEhQKEFNJREVfVU5TUEVDSUZJRUQQABIMCghTSURFX0JVWRABEg0KCVNJREVfU0VMTBACGgSIox4AKloKCU9yZGVyVHlwZRIaChZPUkRFUl9UWVBFX1VOU1BFQ0lGSUVEEAASFAoQT1JERVJfVFlQRV9MSU1JVBABEhUKEU9SREVSX1RZUEVfTUFSS0VUEAIaBIijHgBCN1oxZ2l0aHViLmNvbS9Db3JldW1Gb3VuZGF0aW9uL2NvcmV1bS92NC94L2RleC90eXBlc8jhHgBiBnByb3RvMw", [file_gogoproto_gogo]);

/**
 * Order is a DEX order.
 *
 * @generated from message coreum.dex.v1.Order
 */
export type Order = Message<"coreum.dex.v1.Order"> & {
  /**
   * creator is order creator address.
   *
   * @generated from field: string creator = 1;
   */
  creator: string;

  /**
   * type is order type.
   *
   * @generated from field: coreum.dex.v1.OrderType type = 2;
   */
  type: OrderType;

  /**
   * id is unique order ID.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * base_denom is base order denom.
   *
   * @generated from field: string base_denom = 4;
   */
  baseDenom: string;

  /**
   * quote_denom is quote order denom
   *
   * @generated from field: string quote_denom = 5;
   */
  quoteDenom: string;

  /**
   * price is value of one unit of the base_denom expressed in terms of the quote_denom.
   *
   * @generated from field: string price = 6;
   */
  price: string;

  /**
   * quantity is amount of the base base_denom being traded.
   *
   * @generated from field: string quantity = 7;
   */
  quantity: string;

  /**
   * side is order side.
   *
   * @generated from field: coreum.dex.v1.Side side = 8;
   */
  side: Side;

  /**
   * remaining_quantity is remaining filling quantity sell/buy.
   *
   * @generated from field: string remaining_quantity = 9;
   */
  remainingQuantity: string;

  /**
   * remaining_balance is remaining order balance.
   *
   * @generated from field: string remaining_balance = 10;
   */
  remainingBalance: string;
};

/**
 * Describes the message coreum.dex.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_order, 0);

/**
 * OrderData is a order data used for the store.
 *
 * @generated from message coreum.dex.v1.OrderData
 */
export type OrderData = Message<"coreum.dex.v1.OrderData"> & {
  /**
   * order_book_id is order book ID.
   *
   * @generated from field: uint32 order_book_id = 1;
   */
  orderBookId: number;

  /**
   * price is value of one unit of the base_denom expressed in terms of the quote_denom.
   *
   * @generated from field: string price = 2;
   */
  price: string;

  /**
   * quantity is amount of the base base_denom being traded.
   *
   * @generated from field: string quantity = 3;
   */
  quantity: string;

  /**
   * side is order side.
   *
   * @generated from field: coreum.dex.v1.Side side = 4;
   */
  side: Side;
};

/**
 * Describes the message coreum.dex.v1.OrderData.
 * Use `create(OrderDataSchema)` to create a new message.
 */
export const OrderDataSchema: GenMessage<OrderData> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_order, 1);

/**
 * OrderBookData is a order book data used by order for the store.
 *
 * @generated from message coreum.dex.v1.OrderBookData
 */
export type OrderBookData = Message<"coreum.dex.v1.OrderBookData"> & {
  /**
   * base_denom is base order book denom.
   *
   * @generated from field: string base_denom = 1;
   */
  baseDenom: string;

  /**
   * quote_denom is quote order book denom
   *
   * @generated from field: string quote_denom = 2;
   */
  quoteDenom: string;
};

/**
 * Describes the message coreum.dex.v1.OrderBookData.
 * Use `create(OrderBookDataSchema)` to create a new message.
 */
export const OrderBookDataSchema: GenMessage<OrderBookData> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_order, 2);

/**
 * OrderBookRecord is a single order book record.
 *
 * @generated from message coreum.dex.v1.OrderBookRecord
 */
export type OrderBookRecord = Message<"coreum.dex.v1.OrderBookRecord"> & {
  /**
   * order_book_id is order book ID.
   *
   * @generated from field: uint32 order_book_id = 1;
   */
  orderBookId: number;

  /**
   * side is order side.
   *
   * @generated from field: coreum.dex.v1.Side side = 2;
   */
  side: Side;

  /**
   * price is order book record price.
   *
   * @generated from field: string price = 3;
   */
  price: string;

  /**
   * order_seq is order sequence.
   *
   * @generated from field: uint64 order_seq = 4;
   */
  orderSeq: bigint;

  /**
   * order ID provided by the creator.
   *
   * @generated from field: string order_id = 5;
   */
  orderId: string;

  /**
   * account_number is account number which corresponds the order creator.
   *
   * @generated from field: uint64 account_number = 6;
   */
  accountNumber: bigint;

  /**
   * remaining_quantity is remaining filling quantity sell/buy.
   *
   * @generated from field: string remaining_quantity = 7;
   */
  remainingQuantity: string;

  /**
   * remaining_balance is remaining order balance.
   *
   * @generated from field: string remaining_balance = 8;
   */
  remainingBalance: string;
};

/**
 * Describes the message coreum.dex.v1.OrderBookRecord.
 * Use `create(OrderBookRecordSchema)` to create a new message.
 */
export const OrderBookRecordSchema: GenMessage<OrderBookRecord> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_order, 3);

/**
 * OrderBookRecordData is a single order book record used for the store.
 *
 * @generated from message coreum.dex.v1.OrderBookRecordData
 */
export type OrderBookRecordData = Message<"coreum.dex.v1.OrderBookRecordData"> & {
  /**
   * order ID provided by the creator.
   *
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * account_number is account number which corresponds the order creator.
   *
   * @generated from field: uint64 account_number = 2;
   */
  accountNumber: bigint;

  /**
   * remaining_quantity is remaining filling quantity sell/buy.
   *
   * @generated from field: string remaining_quantity = 3;
   */
  remainingQuantity: string;

  /**
   * remaining_balance is remaining order balance.
   *
   * @generated from field: string remaining_balance = 4;
   */
  remainingBalance: string;
};

/**
 * Describes the message coreum.dex.v1.OrderBookRecordData.
 * Use `create(OrderBookRecordDataSchema)` to create a new message.
 */
export const OrderBookRecordDataSchema: GenMessage<OrderBookRecordData> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_order, 4);

/**
 * Side is order side.
 *
 * @generated from enum coreum.dex.v1.Side
 */
export enum Side {
  /**
   * SIDE_UNSPECIFIED reserves the default value, to protect against unexpected settings.
   *
   * @generated from enum value: SIDE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * SIDE_BUY means that the order is to buy base_denom quantity with the price.
   *
   * @generated from enum value: SIDE_BUY = 1;
   */
  BUY = 1,

  /**
   * SIDE_SELL means that the order is to sell base_denom quantity with the price.
   *
   * @generated from enum value: SIDE_SELL = 2;
   */
  SELL = 2,
}

/**
 * Describes the enum coreum.dex.v1.Side.
 */
export const SideSchema: GenEnum<Side> = /*@__PURE__*/
  enumDesc(file_coreum_dex_v1_order, 0);

/**
 * Type is order type.
 *
 * @generated from enum coreum.dex.v1.OrderType
 */
export enum OrderType {
  /**
   * order_type_unspecified reserves the default value, to protect against unexpected settings.
   *
   * @generated from enum value: ORDER_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * order_type_limit means that the order is limit order.
   *
   * @generated from enum value: ORDER_TYPE_LIMIT = 1;
   */
  LIMIT = 1,

  /**
   * limit order_type_market that the order is market order.
   *
   * @generated from enum value: ORDER_TYPE_MARKET = 2;
   */
  MARKET = 2,
}

/**
 * Describes the enum coreum.dex.v1.OrderType.
 */
export const OrderTypeSchema: GenEnum<OrderType> = /*@__PURE__*/
  enumDesc(file_coreum_dex_v1_order, 1);

