// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/dex/v1/tx.proto (package coreum.dex.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { OrderType, Side } from "./order_pb";
import { file_coreum_dex_v1_order } from "./order_pb";
import type { Params } from "./params_pb";
import { file_coreum_dex_v1_params } from "./params_pb";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/dex/v1/tx.proto.
 */
export const file_coreum_dex_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("ChZjb3JldW0vZGV4L3YxL3R4LnByb3RvEg1jb3JldW0uZGV4LnYxIpgBCg9Nc2dVcGRhdGVQYXJhbXMSKwoJYXV0aG9yaXR5GAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSMAoGcGFyYW1zGAIgASgLMhUuY29yZXVtLmRleC52MS5QYXJhbXNCCcjeHwCo57AqATomguewKglhdXRob3JpdHmK57AqE2RleC9Nc2dVcGRhdGVQYXJhbXMirwIKDU1zZ1BsYWNlT3JkZXISKAoGc2VuZGVyGAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSJgoEdHlwZRgCIAEoDjIYLmNvcmV1bS5kZXgudjEuT3JkZXJUeXBlEhIKAmlkGAMgASgJQgbi3h8CSUQSEgoKYmFzZV9kZW5vbRgEIAEoCRITCgtxdW90ZV9kZW5vbRgFIAEoCRIYCgVwcmljZRgGIAEoCUIJ2t4fBVByaWNlEi8KCHF1YW50aXR5GAcgASgJQh3I3h8A2t4fFWNvc21vc3Nkay5pby9tYXRoLkludBIhCgRzaWRlGAggASgOMhMuY29yZXVtLmRleC52MS5TaWRlOiGC57AqBnNlbmRlcornsCoRZGV4L01zZ1BsYWNlT3JkZXIiWAoOTXNnQ2FuY2VsT3JkZXISDgoGc2VuZGVyGAEgASgJEhIKAmlkGAIgASgJQgbi3h8CSUQ6IoLnsCoGc2VuZGVyiuewKhJkZXgvTXNnQ2FuY2VsT3JkZXIiDwoNRW1wdHlSZXNwb25zZTLwAQoDTXNnEkwKDFVwZGF0ZVBhcmFtcxIeLmNvcmV1bS5kZXgudjEuTXNnVXBkYXRlUGFyYW1zGhwuY29yZXVtLmRleC52MS5FbXB0eVJlc3BvbnNlEkgKClBsYWNlT3JkZXISHC5jb3JldW0uZGV4LnYxLk1zZ1BsYWNlT3JkZXIaHC5jb3JldW0uZGV4LnYxLkVtcHR5UmVzcG9uc2USSgoLQ2FuY2VsT3JkZXISHS5jb3JldW0uZGV4LnYxLk1zZ0NhbmNlbE9yZGVyGhwuY29yZXVtLmRleC52MS5FbXB0eVJlc3BvbnNlGgWA57AqAUI3WjFnaXRodWIuY29tL0NvcmV1bUZvdW5kYXRpb24vY29yZXVtL3Y0L3gvZGV4L3R5cGVzyOEeAGIGcHJvdG8z", [file_amino_amino, file_coreum_dex_v1_order, file_coreum_dex_v1_params, file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * @generated from message coreum.dex.v1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"coreum.dex.v1.MsgUpdateParams"> & {
  /**
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * @generated from field: coreum.dex.v1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message coreum.dex.v1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_tx, 0);

/**
 * MsgPlaceOrder defines message to place an order on orderbook.
 *
 * @generated from message coreum.dex.v1.MsgPlaceOrder
 */
export type MsgPlaceOrder = Message<"coreum.dex.v1.MsgPlaceOrder"> & {
  /**
   * sender is order creator address.
   *
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * type is order type.
   *
   * @generated from field: coreum.dex.v1.OrderType type = 2;
   */
  type: OrderType;

  /**
   * id is unique order ID.
   *
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * base_denom is base order denom.
   *
   * @generated from field: string base_denom = 4;
   */
  baseDenom: string;

  /**
   * quote_denom is quote order denom
   *
   * @generated from field: string quote_denom = 5;
   */
  quoteDenom: string;

  /**
   * price is value of one unit of the base_denom expressed in terms of the quote_denom.
   *
   * @generated from field: string price = 6;
   */
  price: string;

  /**
   * quantity is amount of the base base_denom being traded.
   *
   * @generated from field: string quantity = 7;
   */
  quantity: string;

  /**
   * side is order side.
   *
   * @generated from field: coreum.dex.v1.Side side = 8;
   */
  side: Side;
};

/**
 * Describes the message coreum.dex.v1.MsgPlaceOrder.
 * Use `create(MsgPlaceOrderSchema)` to create a new message.
 */
export const MsgPlaceOrderSchema: GenMessage<MsgPlaceOrder> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_tx, 1);

/**
 * MsgCancelOrder defines message to cancel the order in the orderbook.
 *
 * @generated from message coreum.dex.v1.MsgCancelOrder
 */
export type MsgCancelOrder = Message<"coreum.dex.v1.MsgCancelOrder"> & {
  /**
   * sender is order creator address.
   *
   * @generated from field: string sender = 1;
   */
  sender: string;

  /**
   * id is unique order ID.
   *
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * Describes the message coreum.dex.v1.MsgCancelOrder.
 * Use `create(MsgCancelOrderSchema)` to create a new message.
 */
export const MsgCancelOrderSchema: GenMessage<MsgCancelOrder> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_tx, 2);

/**
 * @generated from message coreum.dex.v1.EmptyResponse
 */
export type EmptyResponse = Message<"coreum.dex.v1.EmptyResponse"> & {
};

/**
 * Describes the message coreum.dex.v1.EmptyResponse.
 * Use `create(EmptyResponseSchema)` to create a new message.
 */
export const EmptyResponseSchema: GenMessage<EmptyResponse> = /*@__PURE__*/
  messageDesc(file_coreum_dex_v1_tx, 3);

/**
 * Msg defines the Msg service.
 *
 * @generated from service coreum.dex.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateParams is a governance operation to modify the parameters of the module.
   * NOTE: all parameters must be provided.
   *
   * @generated from rpc coreum.dex.v1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof EmptyResponseSchema;
  },
  /**
   * PlaceOrder place an order on orderbook.
   *
   * @generated from rpc coreum.dex.v1.Msg.PlaceOrder
   */
  placeOrder: {
    methodKind: "unary";
    input: typeof MsgPlaceOrderSchema;
    output: typeof EmptyResponseSchema;
  },
  /**
   * CancelOrder cancels an order in the orderbook.
   *
   * @generated from rpc coreum.dex.v1.Msg.CancelOrder
   */
  cancelOrder: {
    methodKind: "unary";
    input: typeof MsgCancelOrderSchema;
    output: typeof EmptyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_coreum_dex_v1_tx, 0);

