// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/circuit/v1/types.proto (package cosmos.circuit.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/circuit/v1/types.proto.
 */
export const file_cosmos_circuit_v1_types: GenFile = /*@__PURE__*/
  fileDesc("Ch1jb3Ntb3MvY2lyY3VpdC92MS90eXBlcy5wcm90bxIRY29zbW9zLmNpcmN1aXQudjEiwAEKC1Blcm1pc3Npb25zEjMKBWxldmVsGAEgASgOMiQuY29zbW9zLmNpcmN1aXQudjEuUGVybWlzc2lvbnMuTGV2ZWwSFwoPbGltaXRfdHlwZV91cmxzGAIgAygJImMKBUxldmVsEhoKFkxFVkVMX05PTkVfVU5TUEVDSUZJRUQQABITCg9MRVZFTF9TT01FX01TR1MQARISCg5MRVZFTF9BTExfTVNHUxACEhUKEUxFVkVMX1NVUEVSX0FETUlOEAMiYQoZR2VuZXNpc0FjY291bnRQZXJtaXNzaW9ucxIPCgdhZGRyZXNzGAEgASgJEjMKC3Blcm1pc3Npb25zGAIgASgLMh4uY29zbW9zLmNpcmN1aXQudjEuUGVybWlzc2lvbnMidQoMR2VuZXNpc1N0YXRlEkkKE2FjY291bnRfcGVybWlzc2lvbnMYASADKAsyLC5jb3Ntb3MuY2lyY3VpdC52MS5HZW5lc2lzQWNjb3VudFBlcm1pc3Npb25zEhoKEmRpc2FibGVkX3R5cGVfdXJscxgCIAMoCUIeWhxjb3Ntb3NzZGsuaW8veC9jaXJjdWl0L3R5cGVzYgZwcm90bzM");

/**
 * Permissions are the permissions that an account has to trip
 * or reset the circuit breaker.
 *
 * @generated from message cosmos.circuit.v1.Permissions
 */
export type Permissions = Message<"cosmos.circuit.v1.Permissions"> & {
  /**
   * level is the level of permissions granted to this account.
   *
   * @generated from field: cosmos.circuit.v1.Permissions.Level level = 1;
   */
  level: Permissions_Level;

  /**
   * limit_type_urls is used with LEVEL_SOME_MSGS to limit the lists of Msg type
   * URLs that the account can trip. It is an error to use limit_type_urls with
   * a level other than LEVEL_SOME_MSGS.
   *
   * @generated from field: repeated string limit_type_urls = 2;
   */
  limitTypeUrls: string[];
};

/**
 * Describes the message cosmos.circuit.v1.Permissions.
 * Use `create(PermissionsSchema)` to create a new message.
 */
export const PermissionsSchema: GenMessage<Permissions> = /*@__PURE__*/
  messageDesc(file_cosmos_circuit_v1_types, 0);

/**
 * Level is the permission level.
 *
 * @generated from enum cosmos.circuit.v1.Permissions.Level
 */
export enum Permissions_Level {
  /**
   * LEVEL_NONE_UNSPECIFIED indicates that the account will have no circuit
   * breaker permissions.
   *
   * @generated from enum value: LEVEL_NONE_UNSPECIFIED = 0;
   */
  NONE_UNSPECIFIED = 0,

  /**
   * LEVEL_SOME_MSGS indicates that the account will have permission to
   * trip or reset the circuit breaker for some Msg type URLs. If this level
   * is chosen, a non-empty list of Msg type URLs must be provided in
   * limit_type_urls.
   *
   * @generated from enum value: LEVEL_SOME_MSGS = 1;
   */
  SOME_MSGS = 1,

  /**
   * LEVEL_ALL_MSGS indicates that the account can trip or reset the circuit
   * breaker for Msg's of all type URLs.
   *
   * @generated from enum value: LEVEL_ALL_MSGS = 2;
   */
  ALL_MSGS = 2,

  /**
   * LEVEL_SUPER_ADMIN indicates that the account can take all circuit breaker
   * actions and can grant permissions to other accounts.
   *
   * @generated from enum value: LEVEL_SUPER_ADMIN = 3;
   */
  SUPER_ADMIN = 3,
}

/**
 * Describes the enum cosmos.circuit.v1.Permissions.Level.
 */
export const Permissions_LevelSchema: GenEnum<Permissions_Level> = /*@__PURE__*/
  enumDesc(file_cosmos_circuit_v1_types, 0, 0);

/**
 * GenesisAccountPermissions is the account permissions for the circuit breaker in genesis
 *
 * @generated from message cosmos.circuit.v1.GenesisAccountPermissions
 */
export type GenesisAccountPermissions = Message<"cosmos.circuit.v1.GenesisAccountPermissions"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * @generated from field: cosmos.circuit.v1.Permissions permissions = 2;
   */
  permissions?: Permissions;
};

/**
 * Describes the message cosmos.circuit.v1.GenesisAccountPermissions.
 * Use `create(GenesisAccountPermissionsSchema)` to create a new message.
 */
export const GenesisAccountPermissionsSchema: GenMessage<GenesisAccountPermissions> = /*@__PURE__*/
  messageDesc(file_cosmos_circuit_v1_types, 1);

/**
 * GenesisState is the state that must be provided at genesis.
 *
 * @generated from message cosmos.circuit.v1.GenesisState
 */
export type GenesisState = Message<"cosmos.circuit.v1.GenesisState"> & {
  /**
   * @generated from field: repeated cosmos.circuit.v1.GenesisAccountPermissions account_permissions = 1;
   */
  accountPermissions: GenesisAccountPermissions[];

  /**
   * @generated from field: repeated string disabled_type_urls = 2;
   */
  disabledTypeUrls: string[];
};

/**
 * Describes the message cosmos.circuit.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_cosmos_circuit_v1_types, 2);

