// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file tendermint/crypto/keys.proto (package tendermint.crypto, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tendermint/crypto/keys.proto.
 */
export const file_tendermint_crypto_keys: GenFile = /*@__PURE__*/
  fileDesc("Chx0ZW5kZXJtaW50L2NyeXB0by9rZXlzLnByb3RvEhF0ZW5kZXJtaW50LmNyeXB0byJECglQdWJsaWNLZXkSEQoHZWQyNTUxORgBIAEoDEgAEhMKCXNlY3AyNTZrMRgCIAEoDEgAOgjooB8B6KEfAUIFCgNzdW1CNlo0Z2l0aHViLmNvbS9jb21ldGJmdC9jb21ldGJmdC9wcm90by90ZW5kZXJtaW50L2NyeXB0b2IGcHJvdG8z", [file_gogoproto_gogo]);

/**
 * PublicKey defines the keys available for use with Validators
 *
 * @generated from message tendermint.crypto.PublicKey
 */
export type PublicKey = Message<"tendermint.crypto.PublicKey"> & {
  /**
   * @generated from oneof tendermint.crypto.PublicKey.sum
   */
  sum: {
    /**
     * @generated from field: bytes ed25519 = 1;
     */
    value: Uint8Array;
    case: "ed25519";
  } | {
    /**
     * @generated from field: bytes secp256k1 = 2;
     */
    value: Uint8Array;
    case: "secp256k1";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message tendermint.crypto.PublicKey.
 * Use `create(PublicKeySchema)` to create a new message.
 */
export const PublicKeySchema: GenMessage<PublicKey> = /*@__PURE__*/
  messageDesc(file_tendermint_crypto_keys, 0);

