// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/customparams/v1/genesis.proto (package coreum.customparams.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { StakingParams } from "./params_pb";
import { file_coreum_customparams_v1_params } from "./params_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/customparams/v1/genesis.proto.
 */
export const file_coreum_customparams_v1_genesis: GenFile = /*@__PURE__*/
  fileDesc("CiRjb3JldW0vY3VzdG9tcGFyYW1zL3YxL2dlbmVzaXMucHJvdG8SFmNvcmV1bS5jdXN0b21wYXJhbXMudjEiUwoMR2VuZXNpc1N0YXRlEkMKDnN0YWtpbmdfcGFyYW1zGAEgASgLMiUuY29yZXVtLmN1c3RvbXBhcmFtcy52MS5TdGFraW5nUGFyYW1zQgTI3h8AQjxaOmdpdGh1Yi5jb20vQ29yZXVtRm91bmRhdGlvbi9jb3JldW0vdjQveC9jdXN0b21wYXJhbXMvdHlwZXNiBnByb3RvMw", [file_coreum_customparams_v1_params, file_gogoproto_gogo]);

/**
 * GenesisState defines the module's genesis state.
 *
 * @generated from message coreum.customparams.v1.GenesisState
 */
export type GenesisState = Message<"coreum.customparams.v1.GenesisState"> & {
  /**
   * staking_params defines staking parameters of the module.
   *
   * @generated from field: coreum.customparams.v1.StakingParams staking_params = 1;
   */
  stakingParams?: StakingParams;
};

/**
 * Describes the message coreum.customparams.v1.GenesisState.
 * Use `create(GenesisStateSchema)` to create a new message.
 */
export const GenesisStateSchema: GenMessage<GenesisState> = /*@__PURE__*/
  messageDesc(file_coreum_customparams_v1_genesis, 0);

