// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/customparams/v1/tx.proto (package coreum.customparams.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { StakingParams } from "./params_pb";
import { file_coreum_customparams_v1_params } from "./params_pb";
import { file_cosmos_msg_v1_msg } from "../../../cosmos/msg/v1/msg_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/customparams/v1/tx.proto.
 */
export const file_coreum_customparams_v1_tx: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb3JldW0vY3VzdG9tcGFyYW1zL3YxL3R4LnByb3RvEhZjb3JldW0uY3VzdG9tcGFyYW1zLnYxIsIBChZNc2dVcGRhdGVTdGFraW5nUGFyYW1zEisKCWF1dGhvcml0eRgBIAEoCUIY0rQtFGNvc21vcy5BZGRyZXNzU3RyaW5nEkMKDnN0YWtpbmdfcGFyYW1zGAIgASgLMiUuY29yZXVtLmN1c3RvbXBhcmFtcy52MS5TdGFraW5nUGFyYW1zQgTI3h8AOjaC57AqCWF1dGhvcml0eYrnsCojY3VzdG9tcGFyYW1zL01zZ1VwZGF0ZVN0YWtpbmdQYXJhbXMiDwoNRW1wdHlSZXNwb25zZTJ6CgNNc2cSbAoTVXBkYXRlU3Rha2luZ1BhcmFtcxIuLmNvcmV1bS5jdXN0b21wYXJhbXMudjEuTXNnVXBkYXRlU3Rha2luZ1BhcmFtcxolLmNvcmV1bS5jdXN0b21wYXJhbXMudjEuRW1wdHlSZXNwb25zZRoFgOewKgFCQFo6Z2l0aHViLmNvbS9Db3JldW1Gb3VuZGF0aW9uL2NvcmV1bS92NC94L2N1c3RvbXBhcmFtcy90eXBlc8jhHgBiBnByb3RvMw", [file_amino_amino, file_coreum_customparams_v1_params, file_cosmos_msg_v1_msg, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * @generated from message coreum.customparams.v1.MsgUpdateStakingParams
 */
export type MsgUpdateStakingParams = Message<"coreum.customparams.v1.MsgUpdateStakingParams"> & {
  /**
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * staking_params holds the parameters related to the staking module.
   *
   * @generated from field: coreum.customparams.v1.StakingParams staking_params = 2;
   */
  stakingParams?: StakingParams;
};

/**
 * Describes the message coreum.customparams.v1.MsgUpdateStakingParams.
 * Use `create(MsgUpdateStakingParamsSchema)` to create a new message.
 */
export const MsgUpdateStakingParamsSchema: GenMessage<MsgUpdateStakingParams> = /*@__PURE__*/
  messageDesc(file_coreum_customparams_v1_tx, 0);

/**
 * @generated from message coreum.customparams.v1.EmptyResponse
 */
export type EmptyResponse = Message<"coreum.customparams.v1.EmptyResponse"> & {
};

/**
 * Describes the message coreum.customparams.v1.EmptyResponse.
 * Use `create(EmptyResponseSchema)` to create a new message.
 */
export const EmptyResponseSchema: GenMessage<EmptyResponse> = /*@__PURE__*/
  messageDesc(file_coreum_customparams_v1_tx, 1);

/**
 * Msg defines the Msg service.
 *
 * @generated from service coreum.customparams.v1.Msg
 */
export const Msg: GenService<{
  /**
   * UpdateStakingParams is a governance operation that sets the staking parameter.
   * NOTE: all parameters must be provided.
   *
   * @generated from rpc coreum.customparams.v1.Msg.UpdateStakingParams
   */
  updateStakingParams: {
    methodKind: "unary";
    input: typeof MsgUpdateStakingParamsSchema;
    output: typeof EmptyResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_coreum_customparams_v1_tx, 0);

