// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/bank/module/v1/module.proto (package cosmos.bank.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_app_v1alpha1_module } from "../../../app/v1alpha1/module_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/bank/module/v1/module.proto.
 */
export const file_cosmos_bank_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("CiJjb3Ntb3MvYmFuay9tb2R1bGUvdjEvbW9kdWxlLnByb3RvEhVjb3Ntb3MuYmFuay5tb2R1bGUudjEijgEKBk1vZHVsZRIoCiBibG9ja2VkX21vZHVsZV9hY2NvdW50c19vdmVycmlkZRgBIAMoCRIRCglhdXRob3JpdHkYAiABKAkSGgoScmVzdHJpY3Rpb25zX29yZGVyGAMgAygJOiu6wJbaASUKI2dpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsveC9iYW5rYgZwcm90bzM", [file_cosmos_app_v1alpha1_module]);

/**
 * Module is the config object of the bank module.
 *
 * @generated from message cosmos.bank.module.v1.Module
 */
export type Module = Message<"cosmos.bank.module.v1.Module"> & {
  /**
   * blocked_module_accounts_override configures exceptional module accounts which should be blocked from receiving
   * funds. If left empty it defaults to the list of account names supplied in the auth module configuration as
   * module_account_permissions
   *
   * @generated from field: repeated string blocked_module_accounts_override = 1;
   */
  blockedModuleAccountsOverride: string[];

  /**
   * authority defines the custom module authority. If not set, defaults to the governance module.
   *
   * @generated from field: string authority = 2;
   */
  authority: string;

  /**
   * restrictions_order specifies the order of send restrictions and should be
   * a list of module names which provide a send restriction instance. If no
   * order is provided, then restrictions will be applied in alphabetical order
   * of module names.
   *
   * @generated from field: repeated string restrictions_order = 3;
   */
  restrictionsOrder: string[];
};

/**
 * Describes the message cosmos.bank.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_cosmos_bank_module_v1_module, 0);

