// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/base/v1beta1/coin.proto (package cosmos.base.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/base/v1beta1/coin.proto.
 */
export const file_cosmos_base_v1beta1_coin: GenFile = /*@__PURE__*/
  fileDesc("Ch5jb3Ntb3MvYmFzZS92MWJldGExL2NvaW4ucHJvdG8SE2Nvc21vcy5iYXNlLnYxYmV0YTEiXQoEQ29pbhINCgVkZW5vbRgBIAEoCRJACgZhbW91bnQYAiABKAlCMMjeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnSo57AqAToE6KAfASJhCgdEZWNDb2luEg0KBWRlbm9tGAEgASgJEkEKBmFtb3VudBgCIAEoCUIxyN4fANreHxtjb3Ntb3NzZGsuaW8vbWF0aC5MZWdhY3lEZWPStC0KY29zbW9zLkRlYzoE6KAfASJECghJbnRQcm90bxI4CgNpbnQYASABKAlCK8jeHwDa3h8VY29zbW9zc2RrLmlvL21hdGguSW500rQtCmNvc21vcy5JbnQiSgoIRGVjUHJvdG8SPgoDZGVjGAEgASgJQjHI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjQixaImdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXPY4R4AgOIeAGIGcHJvdG8z", [file_gogoproto_gogo, file_cosmos_proto_cosmos, file_amino_amino]);

/**
 * Coin defines a token with a denomination and an amount.
 *
 * NOTE: The amount field is an Int which implements the custom method
 * signatures required by gogoproto.
 *
 * @generated from message cosmos.base.v1beta1.Coin
 */
export type Coin = Message<"cosmos.base.v1beta1.Coin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message cosmos.base.v1beta1.Coin.
 * Use `create(CoinSchema)` to create a new message.
 */
export const CoinSchema: GenMessage<Coin> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 0);

/**
 * DecCoin defines a token with a denomination and a decimal amount.
 *
 * NOTE: The amount field is an Dec which implements the custom method
 * signatures required by gogoproto.
 *
 * @generated from message cosmos.base.v1beta1.DecCoin
 */
export type DecCoin = Message<"cosmos.base.v1beta1.DecCoin"> & {
  /**
   * @generated from field: string denom = 1;
   */
  denom: string;

  /**
   * @generated from field: string amount = 2;
   */
  amount: string;
};

/**
 * Describes the message cosmos.base.v1beta1.DecCoin.
 * Use `create(DecCoinSchema)` to create a new message.
 */
export const DecCoinSchema: GenMessage<DecCoin> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 1);

/**
 * IntProto defines a Protobuf wrapper around an Int object.
 * Deprecated: Prefer to use math.Int directly. It supports binary Marshal and Unmarshal.
 *
 * @generated from message cosmos.base.v1beta1.IntProto
 */
export type IntProto = Message<"cosmos.base.v1beta1.IntProto"> & {
  /**
   * @generated from field: string int = 1;
   */
  int: string;
};

/**
 * Describes the message cosmos.base.v1beta1.IntProto.
 * Use `create(IntProtoSchema)` to create a new message.
 */
export const IntProtoSchema: GenMessage<IntProto> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 2);

/**
 * DecProto defines a Protobuf wrapper around a Dec object.
 * Deprecated: Prefer to use math.LegacyDec directly. It supports binary Marshal and Unmarshal.
 *
 * @generated from message cosmos.base.v1beta1.DecProto
 */
export type DecProto = Message<"cosmos.base.v1beta1.DecProto"> & {
  /**
   * @generated from field: string dec = 1;
   */
  dec: string;
};

/**
 * Describes the message cosmos.base.v1beta1.DecProto.
 * Use `create(DecProtoSchema)` to create a new message.
 */
export const DecProtoSchema: GenMessage<DecProto> = /*@__PURE__*/
  messageDesc(file_cosmos_base_v1beta1_coin, 3);

