// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/evidence/module/v1/module.proto (package cosmos.evidence.module.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_cosmos_app_v1alpha1_module } from "../../../app/v1alpha1/module_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/evidence/module/v1/module.proto.
 */
export const file_cosmos_evidence_module_v1_module: GenFile = /*@__PURE__*/
  fileDesc("CiZjb3Ntb3MvZXZpZGVuY2UvbW9kdWxlL3YxL21vZHVsZS5wcm90bxIZY29zbW9zLmV2aWRlbmNlLm1vZHVsZS52MSIpCgZNb2R1bGU6H7rAltoBGQoXY29zbW9zc2RrLmlvL3gvZXZpZGVuY2ViBnByb3RvMw", [file_cosmos_app_v1alpha1_module]);

/**
 * Module is the config object of the evidence module.
 *
 * @generated from message cosmos.evidence.module.v1.Module
 */
export type Module = Message<"cosmos.evidence.module.v1.Module"> & {
};

/**
 * Describes the message cosmos.evidence.module.v1.Module.
 * Use `create(ModuleSchema)` to create a new message.
 */
export const ModuleSchema: GenMessage<Module> = /*@__PURE__*/
  messageDesc(file_cosmos_evidence_module_v1_module, 0);

