// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file coreum/asset/ft/v1/authz.proto (package coreum.asset.ft.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../../amino/amino_pb";
import type { Coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../../../cosmos/base/v1beta1/coin_pb";
import { file_cosmos_proto_cosmos } from "../../../../cosmos_proto/cosmos_pb";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file coreum/asset/ft/v1/authz.proto.
 */
export const file_coreum_asset_ft_v1_authz: GenFile = /*@__PURE__*/
  fileDesc("Ch5jb3JldW0vYXNzZXQvZnQvdjEvYXV0aHoucHJvdG8SEmNvcmV1bS5hc3NldC5mdC52MSK/AQoRTWludEF1dGhvcml6YXRpb24SZAoKbWludF9saW1pdBgBIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkI1yN4fAKrfHyhnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzLkNvaW5zqOewKgA6RMq0LSJjb3Ntb3MuYXV0aHoudjFiZXRhMS5BdXRob3JpemF0aW9uiuewKhlhc3NldGZ0L01pbnRBdXRob3JpemF0aW9uIr8BChFCdXJuQXV0aG9yaXphdGlvbhJkCgpidXJuX2xpbWl0GAEgAygLMhkuY29zbW9zLmJhc2UudjFiZXRhMS5Db2luQjXI3h8Aqt8fKGdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsvdHlwZXMuQ29pbnOo57AqADpEyrQtImNvc21vcy5hdXRoei52MWJldGExLkF1dGhvcml6YXRpb26K57AqGWFzc2V0ZnQvQnVybkF1dGhvcml6YXRpb25COFo2Z2l0aHViLmNvbS9Db3JldW1Gb3VuZGF0aW9uL2NvcmV1bS92NC94L2Fzc2V0L2Z0L3R5cGVzYgZwcm90bzM", [file_amino_amino, file_cosmos_base_v1beta1_coin, file_cosmos_proto_cosmos, file_gogoproto_gogo]);

/**
 * MintAuthorization allows the grantee to mint up to mint_limit coin from
 * the granter's account.
 *
 * @generated from message coreum.asset.ft.v1.MintAuthorization
 */
export type MintAuthorization = Message<"coreum.asset.ft.v1.MintAuthorization"> & {
  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin mint_limit = 1;
   */
  mintLimit: Coin[];
};

/**
 * Describes the message coreum.asset.ft.v1.MintAuthorization.
 * Use `create(MintAuthorizationSchema)` to create a new message.
 */
export const MintAuthorizationSchema: GenMessage<MintAuthorization> = /*@__PURE__*/
  messageDesc(file_coreum_asset_ft_v1_authz, 0);

/**
 * BurnAuthorization allows the grantee to burn up to burn_limit coin from
 * the granter's account.
 *
 * @generated from message coreum.asset.ft.v1.BurnAuthorization
 */
export type BurnAuthorization = Message<"coreum.asset.ft.v1.BurnAuthorization"> & {
  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin burn_limit = 1;
   */
  burnLimit: Coin[];
};

/**
 * Describes the message coreum.asset.ft.v1.BurnAuthorization.
 * Use `create(BurnAuthorizationSchema)` to create a new message.
 */
export const BurnAuthorizationSchema: GenMessage<BurnAuthorization> = /*@__PURE__*/
  messageDesc(file_coreum_asset_ft_v1_authz, 1);

