// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file tendermint/types/validator.proto (package tendermint.types, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../gogoproto/gogo_pb";
import type { PublicKey } from "../crypto/keys_pb";
import { file_tendermint_crypto_keys } from "../crypto/keys_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tendermint/types/validator.proto.
 */
export const file_tendermint_types_validator: GenFile = /*@__PURE__*/
  fileDesc("CiB0ZW5kZXJtaW50L3R5cGVzL3ZhbGlkYXRvci5wcm90bxIQdGVuZGVybWludC50eXBlcyKKAQoMVmFsaWRhdG9yU2V0Ei8KCnZhbGlkYXRvcnMYASADKAsyGy50ZW5kZXJtaW50LnR5cGVzLlZhbGlkYXRvchItCghwcm9wb3NlchgCIAEoCzIbLnRlbmRlcm1pbnQudHlwZXMuVmFsaWRhdG9yEhoKEnRvdGFsX3ZvdGluZ19wb3dlchgDIAEoAyKCAQoJVmFsaWRhdG9yEg8KB2FkZHJlc3MYASABKAwSMwoHcHViX2tleRgCIAEoCzIcLnRlbmRlcm1pbnQuY3J5cHRvLlB1YmxpY0tleUIEyN4fABIUCgx2b3RpbmdfcG93ZXIYAyABKAMSGQoRcHJvcG9zZXJfcHJpb3JpdHkYBCABKAMiVgoPU2ltcGxlVmFsaWRhdG9yEi0KB3B1Yl9rZXkYASABKAsyHC50ZW5kZXJtaW50LmNyeXB0by5QdWJsaWNLZXkSFAoMdm90aW5nX3Bvd2VyGAIgASgDKtcBCgtCbG9ja0lERmxhZxIxChVCTE9DS19JRF9GTEFHX1VOS05PV04QABoWip0gEkJsb2NrSURGbGFnVW5rbm93bhIvChRCTE9DS19JRF9GTEFHX0FCU0VOVBABGhWKnSARQmxvY2tJREZsYWdBYnNlbnQSLwoUQkxPQ0tfSURfRkxBR19DT01NSVQQAhoVip0gEUJsb2NrSURGbGFnQ29tbWl0EikKEUJMT0NLX0lEX0ZMQUdfTklMEAMaEoqdIA5CbG9ja0lERmxhZ05pbBoIiKMeAKikHgFCNVozZ2l0aHViLmNvbS9jb21ldGJmdC9jb21ldGJmdC9wcm90by90ZW5kZXJtaW50L3R5cGVzYgZwcm90bzM", [file_gogoproto_gogo, file_tendermint_crypto_keys]);

/**
 * @generated from message tendermint.types.ValidatorSet
 */
export type ValidatorSet = Message<"tendermint.types.ValidatorSet"> & {
  /**
   * @generated from field: repeated tendermint.types.Validator validators = 1;
   */
  validators: Validator[];

  /**
   * @generated from field: tendermint.types.Validator proposer = 2;
   */
  proposer?: Validator;

  /**
   * @generated from field: int64 total_voting_power = 3;
   */
  totalVotingPower: bigint;
};

/**
 * Describes the message tendermint.types.ValidatorSet.
 * Use `create(ValidatorSetSchema)` to create a new message.
 */
export const ValidatorSetSchema: GenMessage<ValidatorSet> = /*@__PURE__*/
  messageDesc(file_tendermint_types_validator, 0);

/**
 * @generated from message tendermint.types.Validator
 */
export type Validator = Message<"tendermint.types.Validator"> & {
  /**
   * @generated from field: bytes address = 1;
   */
  address: Uint8Array;

  /**
   * @generated from field: tendermint.crypto.PublicKey pub_key = 2;
   */
  pubKey?: PublicKey;

  /**
   * @generated from field: int64 voting_power = 3;
   */
  votingPower: bigint;

  /**
   * @generated from field: int64 proposer_priority = 4;
   */
  proposerPriority: bigint;
};

/**
 * Describes the message tendermint.types.Validator.
 * Use `create(ValidatorSchema)` to create a new message.
 */
export const ValidatorSchema: GenMessage<Validator> = /*@__PURE__*/
  messageDesc(file_tendermint_types_validator, 1);

/**
 * @generated from message tendermint.types.SimpleValidator
 */
export type SimpleValidator = Message<"tendermint.types.SimpleValidator"> & {
  /**
   * @generated from field: tendermint.crypto.PublicKey pub_key = 1;
   */
  pubKey?: PublicKey;

  /**
   * @generated from field: int64 voting_power = 2;
   */
  votingPower: bigint;
};

/**
 * Describes the message tendermint.types.SimpleValidator.
 * Use `create(SimpleValidatorSchema)` to create a new message.
 */
export const SimpleValidatorSchema: GenMessage<SimpleValidator> = /*@__PURE__*/
  messageDesc(file_tendermint_types_validator, 2);

/**
 * BlockIdFlag indicates which BlockID the signature is for
 *
 * @generated from enum tendermint.types.BlockIDFlag
 */
export enum BlockIDFlag {
  /**
   * indicates an error condition
   *
   * @generated from enum value: BLOCK_ID_FLAG_UNKNOWN = 0;
   */
  BLOCK_ID_FLAG_UNKNOWN = 0,

  /**
   * the vote was not received
   *
   * @generated from enum value: BLOCK_ID_FLAG_ABSENT = 1;
   */
  BLOCK_ID_FLAG_ABSENT = 1,

  /**
   * voted for the block that received the majority
   *
   * @generated from enum value: BLOCK_ID_FLAG_COMMIT = 2;
   */
  BLOCK_ID_FLAG_COMMIT = 2,

  /**
   * voted for nil
   *
   * @generated from enum value: BLOCK_ID_FLAG_NIL = 3;
   */
  BLOCK_ID_FLAG_NIL = 3,
}

/**
 * Describes the enum tendermint.types.BlockIDFlag.
 */
export const BlockIDFlagSchema: GenEnum<BlockIDFlag> = /*@__PURE__*/
  enumDesc(file_tendermint_types_validator, 0);

