// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/base/node/v1beta1/query.proto (package cosmos.base.node.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_gogoproto_gogo } from "../../../../gogoproto/gogo_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/base/node/v1beta1/query.proto.
 */
export const file_cosmos_base_node_v1beta1_query: GenFile = /*@__PURE__*/
  fileDesc("CiRjb3Ntb3MvYmFzZS9ub2RlL3YxYmV0YTEvcXVlcnkucHJvdG8SGGNvc21vcy5iYXNlLm5vZGUudjFiZXRhMSIPCg1Db25maWdSZXF1ZXN0IncKDkNvbmZpZ1Jlc3BvbnNlEhkKEW1pbmltdW1fZ2FzX3ByaWNlGAEgASgJEhsKE3BydW5pbmdfa2VlcF9yZWNlbnQYAiABKAkSGAoQcHJ1bmluZ19pbnRlcnZhbBgDIAEoCRITCgtoYWx0X2hlaWdodBgEIAEoBCIPCg1TdGF0dXNSZXF1ZXN0Ip4BCg5TdGF0dXNSZXNwb25zZRIdChVlYXJsaWVzdF9zdG9yZV9oZWlnaHQYASABKAQSDgoGaGVpZ2h0GAIgASgEEjMKCXRpbWVzdGFtcBgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCBJDfHwESEAoIYXBwX2hhc2gYBCABKAwSFgoOdmFsaWRhdG9yX2hhc2gYBSABKAwymQIKB1NlcnZpY2UShQEKBkNvbmZpZxInLmNvc21vcy5iYXNlLm5vZGUudjFiZXRhMS5Db25maWdSZXF1ZXN0GiguY29zbW9zLmJhc2Uubm9kZS52MWJldGExLkNvbmZpZ1Jlc3BvbnNlIiiC0+STAiISIC9jb3Ntb3MvYmFzZS9ub2RlL3YxYmV0YTEvY29uZmlnEoUBCgZTdGF0dXMSJy5jb3Ntb3MuYmFzZS5ub2RlLnYxYmV0YTEuU3RhdHVzUmVxdWVzdBooLmNvc21vcy5iYXNlLm5vZGUudjFiZXRhMS5TdGF0dXNSZXNwb25zZSIogtPkkwIiEiAvY29zbW9zL2Jhc2Uvbm9kZS92MWJldGExL3N0YXR1c0IvWi1naXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL2NsaWVudC9ncnBjL25vZGViBnByb3RvMw", [file_google_api_annotations, file_google_protobuf_timestamp, file_gogoproto_gogo]);

/**
 * ConfigRequest defines the request structure for the Config gRPC query.
 *
 * @generated from message cosmos.base.node.v1beta1.ConfigRequest
 */
export type ConfigRequest = Message<"cosmos.base.node.v1beta1.ConfigRequest"> & {
};

/**
 * Describes the message cosmos.base.node.v1beta1.ConfigRequest.
 * Use `create(ConfigRequestSchema)` to create a new message.
 */
export const ConfigRequestSchema: GenMessage<ConfigRequest> = /*@__PURE__*/
  messageDesc(file_cosmos_base_node_v1beta1_query, 0);

/**
 * ConfigResponse defines the response structure for the Config gRPC query.
 *
 * @generated from message cosmos.base.node.v1beta1.ConfigResponse
 */
export type ConfigResponse = Message<"cosmos.base.node.v1beta1.ConfigResponse"> & {
  /**
   * @generated from field: string minimum_gas_price = 1;
   */
  minimumGasPrice: string;

  /**
   * @generated from field: string pruning_keep_recent = 2;
   */
  pruningKeepRecent: string;

  /**
   * @generated from field: string pruning_interval = 3;
   */
  pruningInterval: string;

  /**
   * @generated from field: uint64 halt_height = 4;
   */
  haltHeight: bigint;
};

/**
 * Describes the message cosmos.base.node.v1beta1.ConfigResponse.
 * Use `create(ConfigResponseSchema)` to create a new message.
 */
export const ConfigResponseSchema: GenMessage<ConfigResponse> = /*@__PURE__*/
  messageDesc(file_cosmos_base_node_v1beta1_query, 1);

/**
 * StateRequest defines the request structure for the status of a node.
 *
 * @generated from message cosmos.base.node.v1beta1.StatusRequest
 */
export type StatusRequest = Message<"cosmos.base.node.v1beta1.StatusRequest"> & {
};

/**
 * Describes the message cosmos.base.node.v1beta1.StatusRequest.
 * Use `create(StatusRequestSchema)` to create a new message.
 */
export const StatusRequestSchema: GenMessage<StatusRequest> = /*@__PURE__*/
  messageDesc(file_cosmos_base_node_v1beta1_query, 2);

/**
 * StateResponse defines the response structure for the status of a node.
 *
 * @generated from message cosmos.base.node.v1beta1.StatusResponse
 */
export type StatusResponse = Message<"cosmos.base.node.v1beta1.StatusResponse"> & {
  /**
   * earliest block height available in the store
   *
   * @generated from field: uint64 earliest_store_height = 1;
   */
  earliestStoreHeight: bigint;

  /**
   * current block height
   *
   * @generated from field: uint64 height = 2;
   */
  height: bigint;

  /**
   * block height timestamp
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 3;
   */
  timestamp?: Timestamp;

  /**
   * app hash of the current block
   *
   * @generated from field: bytes app_hash = 4;
   */
  appHash: Uint8Array;

  /**
   * validator hash provided by the consensus header
   *
   * @generated from field: bytes validator_hash = 5;
   */
  validatorHash: Uint8Array;
};

/**
 * Describes the message cosmos.base.node.v1beta1.StatusResponse.
 * Use `create(StatusResponseSchema)` to create a new message.
 */
export const StatusResponseSchema: GenMessage<StatusResponse> = /*@__PURE__*/
  messageDesc(file_cosmos_base_node_v1beta1_query, 3);

/**
 * Service defines the gRPC querier service for node related queries.
 *
 * @generated from service cosmos.base.node.v1beta1.Service
 */
export const Service: GenService<{
  /**
   * Config queries for the operator configuration.
   *
   * @generated from rpc cosmos.base.node.v1beta1.Service.Config
   */
  config: {
    methodKind: "unary";
    input: typeof ConfigRequestSchema;
    output: typeof ConfigResponseSchema;
  },
  /**
   * Status queries for the node status.
   *
   * @generated from rpc cosmos.base.node.v1beta1.Service.Status
   */
  status: {
    methodKind: "unary";
    input: typeof StatusRequestSchema;
    output: typeof StatusResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_cosmos_base_node_v1beta1_query, 0);

