// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/orm/v1alpha1/schema.proto (package cosmos.orm.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenExtension, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, extDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { MessageOptions } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_descriptor } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/orm/v1alpha1/schema.proto.
 */
export const file_cosmos_orm_v1alpha1_schema: GenFile = /*@__PURE__*/
  fileDesc("CiBjb3Ntb3Mvb3JtL3YxYWxwaGExL3NjaGVtYS5wcm90bxITY29zbW9zLm9ybS52MWFscGhhMSLeAQoWTW9kdWxlU2NoZW1hRGVzY3JpcHRvchJKCgtzY2hlbWFfZmlsZRgBIAMoCzI1LmNvc21vcy5vcm0udjFhbHBoYTEuTW9kdWxlU2NoZW1hRGVzY3JpcHRvci5GaWxlRW50cnkSDgoGcHJlZml4GAIgASgMGmgKCUZpbGVFbnRyeRIKCgJpZBgBIAEoDRIXCg9wcm90b19maWxlX25hbWUYAiABKAkSNgoMc3RvcmFnZV90eXBlGAMgASgOMiAuY29zbW9zLm9ybS52MWFscGhhMS5TdG9yYWdlVHlwZSpoCgtTdG9yYWdlVHlwZRIkCiBTVE9SQUdFX1RZUEVfREVGQVVMVF9VTlNQRUNJRklFRBAAEhcKE1NUT1JBR0VfVFlQRV9NRU1PUlkQARIaChZTVE9SQUdFX1RZUEVfVFJBTlNJRU5UEAI6dAoNbW9kdWxlX3NjaGVtYRIfLmdvb2dsZS5wcm90b2J1Zi5NZXNzYWdlT3B0aW9ucxjws+oxIAEoCzIrLmNvc21vcy5vcm0udjFhbHBoYTEuTW9kdWxlU2NoZW1hRGVzY3JpcHRvclIMbW9kdWxlU2NoZW1hYgZwcm90bzM", [file_google_protobuf_descriptor]);

/**
 * ModuleSchemaDescriptor describe's a module's ORM schema.
 *
 * @generated from message cosmos.orm.v1alpha1.ModuleSchemaDescriptor
 */
export type ModuleSchemaDescriptor = Message<"cosmos.orm.v1alpha1.ModuleSchemaDescriptor"> & {
  /**
   * @generated from field: repeated cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry schema_file = 1;
   */
  schemaFile: ModuleSchemaDescriptor_FileEntry[];

  /**
   * prefix is an optional prefix that precedes all keys in this module's
   * store.
   *
   * @generated from field: bytes prefix = 2;
   */
  prefix: Uint8Array;
};

/**
 * Describes the message cosmos.orm.v1alpha1.ModuleSchemaDescriptor.
 * Use `create(ModuleSchemaDescriptorSchema)` to create a new message.
 */
export const ModuleSchemaDescriptorSchema: GenMessage<ModuleSchemaDescriptor> = /*@__PURE__*/
  messageDesc(file_cosmos_orm_v1alpha1_schema, 0);

/**
 * FileEntry describes an ORM file used in a module.
 *
 * @generated from message cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry
 */
export type ModuleSchemaDescriptor_FileEntry = Message<"cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry"> & {
  /**
   * id is a prefix that will be varint encoded and prepended to all the
   * table keys specified in the file's tables.
   *
   * @generated from field: uint32 id = 1;
   */
  id: number;

  /**
   * proto_file_name is the name of a file .proto in that contains
   * table definitions. The .proto file must be in a package that the
   * module has referenced using cosmos.app.v1.ModuleDescriptor.use_package.
   *
   * @generated from field: string proto_file_name = 2;
   */
  protoFileName: string;

  /**
   * storage_type optionally indicates the type of storage this file's
   * tables should used. If it is left unspecified, the default KV-storage
   * of the app will be used.
   *
   * @generated from field: cosmos.orm.v1alpha1.StorageType storage_type = 3;
   */
  storageType: StorageType;
};

/**
 * Describes the message cosmos.orm.v1alpha1.ModuleSchemaDescriptor.FileEntry.
 * Use `create(ModuleSchemaDescriptor_FileEntrySchema)` to create a new message.
 */
export const ModuleSchemaDescriptor_FileEntrySchema: GenMessage<ModuleSchemaDescriptor_FileEntry> = /*@__PURE__*/
  messageDesc(file_cosmos_orm_v1alpha1_schema, 0, 0);

/**
 * StorageType
 *
 * @generated from enum cosmos.orm.v1alpha1.StorageType
 */
export enum StorageType {
  /**
   * STORAGE_TYPE_DEFAULT_UNSPECIFIED indicates the persistent storage where all
   * data is stored in the regular Merkle-tree backed KV-store.
   *
   * @generated from enum value: STORAGE_TYPE_DEFAULT_UNSPECIFIED = 0;
   */
  DEFAULT_UNSPECIFIED = 0,

  /**
   * STORAGE_TYPE_MEMORY indicates in-memory storage that will be
   * reloaded every time an app restarts. Tables with this type of storage
   * will by default be ignored when importing and exporting a module's
   * state from JSON.
   *
   * @generated from enum value: STORAGE_TYPE_MEMORY = 1;
   */
  MEMORY = 1,

  /**
   * STORAGE_TYPE_TRANSIENT indicates transient storage that is reset
   * at the end of every block. Tables with this type of storage
   * will by default be ignored when importing and exporting a module's
   * state from JSON.
   *
   * @generated from enum value: STORAGE_TYPE_TRANSIENT = 2;
   */
  TRANSIENT = 2,
}

/**
 * Describes the enum cosmos.orm.v1alpha1.StorageType.
 */
export const StorageTypeSchema: GenEnum<StorageType> = /*@__PURE__*/
  enumDesc(file_cosmos_orm_v1alpha1_schema, 0);

/**
 * module_schema is used to define the ORM schema for an app module.
 * All module config messages that use module_schema must also declare
 * themselves as app module config messages using the cosmos.app.v1.is_module
 * option.
 *
 * @generated from extension: cosmos.orm.v1alpha1.ModuleSchemaDescriptor module_schema = 104503792;
 */
export const module_schema: GenExtension<MessageOptions, ModuleSchemaDescriptor> = /*@__PURE__*/
  extDesc(file_cosmos_orm_v1alpha1_schema, 0);

