// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/bank/v1beta1/authz.proto (package cosmos.bank.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_amino_amino } from "../../../amino/amino_pb";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import type { Coin } from "../../base/v1beta1/coin_pb";
import { file_cosmos_base_v1beta1_coin } from "../../base/v1beta1/coin_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/bank/v1beta1/authz.proto.
 */
export const file_cosmos_bank_v1beta1_authz: GenFile = /*@__PURE__*/
  fileDesc("Ch9jb3Ntb3MvYmFuay92MWJldGExL2F1dGh6LnByb3RvEhNjb3Ntb3MuYmFuay52MWJldGExIoICChFTZW5kQXV0aG9yaXphdGlvbhJ2CgtzcGVuZF9saW1pdBgBIAMoCzIZLmNvc21vcy5iYXNlLnYxYmV0YTEuQ29pbkJGyN4fAKrfHyhnaXRodWIuY29tL2Nvc21vcy9jb3Ntb3Mtc2RrL3R5cGVzLkNvaW5zmuewKgxsZWdhY3lfY29pbnOo57AqARIsCgphbGxvd19saXN0GAIgAygJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmc6R8q0LSJjb3Ntb3MuYXV0aHoudjFiZXRhMS5BdXRob3JpemF0aW9uiuewKhxjb3Ntb3Mtc2RrL1NlbmRBdXRob3JpemF0aW9uQitaKWdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsveC9iYW5rL3R5cGVzYgZwcm90bzM", [file_amino_amino, file_gogoproto_gogo, file_cosmos_proto_cosmos, file_cosmos_base_v1beta1_coin]);

/**
 * SendAuthorization allows the grantee to spend up to spend_limit coins from
 * the granter's account.
 *
 * Since: cosmos-sdk 0.43
 *
 * @generated from message cosmos.bank.v1beta1.SendAuthorization
 */
export type SendAuthorization = Message<"cosmos.bank.v1beta1.SendAuthorization"> & {
  /**
   * @generated from field: repeated cosmos.base.v1beta1.Coin spend_limit = 1;
   */
  spendLimit: Coin[];

  /**
   * allow_list specifies an optional list of addresses to whom the grantee can send tokens on behalf of the
   * granter. If omitted, any recipient is allowed.
   *
   * Since: cosmos-sdk 0.47
   *
   * @generated from field: repeated string allow_list = 2;
   */
  allowList: string[];
};

/**
 * Describes the message cosmos.bank.v1beta1.SendAuthorization.
 * Use `create(SendAuthorizationSchema)` to create a new message.
 */
export const SendAuthorizationSchema: GenMessage<SendAuthorization> = /*@__PURE__*/
  messageDesc(file_cosmos_bank_v1beta1_authz, 0);

