// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/slashing/v1beta1/slashing.proto (package cosmos.slashing.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Duration, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/slashing/v1beta1/slashing.proto.
 */
export const file_cosmos_slashing_v1beta1_slashing: GenFile = /*@__PURE__*/
  fileDesc("CiZjb3Ntb3Mvc2xhc2hpbmcvdjFiZXRhMS9zbGFzaGluZy5wcm90bxIXY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEi8AEKFFZhbGlkYXRvclNpZ25pbmdJbmZvEjIKB2FkZHJlc3MYASABKAlCIdK0LR1jb3Ntb3MuQ29uc2Vuc3VzQWRkcmVzc1N0cmluZxIUCgxzdGFydF9oZWlnaHQYAiABKAMSFAoMaW5kZXhfb2Zmc2V0GAMgASgDEj8KDGphaWxlZF91bnRpbBgEIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCDcjeHwCQ3x8BqOewKgESEgoKdG9tYnN0b25lZBgFIAEoCBIdChVtaXNzZWRfYmxvY2tzX2NvdW50ZXIYBiABKAM6BOigHwEinwMKBlBhcmFtcxIcChRzaWduZWRfYmxvY2tzX3dpbmRvdxgBIAEoAxJVChVtaW5fc2lnbmVkX3Blcl93aW5kb3cYAiABKAxCNsjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWOo57AqARJIChZkb3dudGltZV9qYWlsX2R1cmF0aW9uGAMgASgLMhkuZ29vZ2xlLnByb3RvYnVmLkR1cmF0aW9uQg3I3h8AmN8fAajnsCoBEloKGnNsYXNoX2ZyYWN0aW9uX2RvdWJsZV9zaWduGAQgASgMQjbI3h8A2t4fG2Nvc21vc3Nkay5pby9tYXRoLkxlZ2FjeURlY9K0LQpjb3Ntb3MuRGVjqOewKgESVwoXc2xhc2hfZnJhY3Rpb25fZG93bnRpbWUYBSABKAxCNsjeHwDa3h8bY29zbW9zc2RrLmlvL21hdGguTGVnYWN5RGVj0rQtCmNvc21vcy5EZWOo57AqATohiuewKhxjb3Ntb3Mtc2RrL3gvc2xhc2hpbmcvUGFyYW1zQjNaLWdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsveC9zbGFzaGluZy90eXBlc6jiHgFiBnByb3RvMw", [file_gogoproto_gogo, file_google_protobuf_duration, file_google_protobuf_timestamp, file_cosmos_proto_cosmos, file_amino_amino]);

/**
 * ValidatorSigningInfo defines a validator's signing info for monitoring their
 * liveness activity.
 *
 * @generated from message cosmos.slashing.v1beta1.ValidatorSigningInfo
 */
export type ValidatorSigningInfo = Message<"cosmos.slashing.v1beta1.ValidatorSigningInfo"> & {
  /**
   * @generated from field: string address = 1;
   */
  address: string;

  /**
   * Height at which validator was first a candidate OR was un-jailed
   *
   * @generated from field: int64 start_height = 2;
   */
  startHeight: bigint;

  /**
   * Index which is incremented every time a validator is bonded in a block and
   * _may_ have signed a pre-commit or not. This in conjunction with the
   * signed_blocks_window param determines the index in the missed block bitmap.
   *
   * @generated from field: int64 index_offset = 3;
   */
  indexOffset: bigint;

  /**
   * Timestamp until which the validator is jailed due to liveness downtime.
   *
   * @generated from field: google.protobuf.Timestamp jailed_until = 4;
   */
  jailedUntil?: Timestamp;

  /**
   * Whether or not a validator has been tombstoned (killed out of validator
   * set). It is set once the validator commits an equivocation or for any other
   * configured misbehavior.
   *
   * @generated from field: bool tombstoned = 5;
   */
  tombstoned: boolean;

  /**
   * A counter of missed (unsigned) blocks. It is used to avoid unnecessary
   * reads in the missed block bitmap.
   *
   * @generated from field: int64 missed_blocks_counter = 6;
   */
  missedBlocksCounter: bigint;
};

/**
 * Describes the message cosmos.slashing.v1beta1.ValidatorSigningInfo.
 * Use `create(ValidatorSigningInfoSchema)` to create a new message.
 */
export const ValidatorSigningInfoSchema: GenMessage<ValidatorSigningInfo> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_slashing, 0);

/**
 * Params represents the parameters used for by the slashing module.
 *
 * @generated from message cosmos.slashing.v1beta1.Params
 */
export type Params = Message<"cosmos.slashing.v1beta1.Params"> & {
  /**
   * @generated from field: int64 signed_blocks_window = 1;
   */
  signedBlocksWindow: bigint;

  /**
   * @generated from field: bytes min_signed_per_window = 2;
   */
  minSignedPerWindow: Uint8Array;

  /**
   * @generated from field: google.protobuf.Duration downtime_jail_duration = 3;
   */
  downtimeJailDuration?: Duration;

  /**
   * @generated from field: bytes slash_fraction_double_sign = 4;
   */
  slashFractionDoubleSign: Uint8Array;

  /**
   * @generated from field: bytes slash_fraction_downtime = 5;
   */
  slashFractionDowntime: Uint8Array;
};

/**
 * Describes the message cosmos.slashing.v1beta1.Params.
 * Use `create(ParamsSchema)` to create a new message.
 */
export const ParamsSchema: GenMessage<Params> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_slashing, 1);

