// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file cosmos/slashing/v1beta1/tx.proto (package cosmos.slashing.v1beta1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_gogoproto_gogo } from "../../../gogoproto/gogo_pb";
import type { Params } from "./slashing_pb";
import { file_cosmos_slashing_v1beta1_slashing } from "./slashing_pb";
import { file_cosmos_proto_cosmos } from "../../../cosmos_proto/cosmos_pb";
import { file_cosmos_msg_v1_msg } from "../../msg/v1/msg_pb";
import { file_amino_amino } from "../../../amino/amino_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file cosmos/slashing/v1beta1/tx.proto.
 */
export const file_cosmos_slashing_v1beta1_tx: GenFile = /*@__PURE__*/
  fileDesc("CiBjb3Ntb3Mvc2xhc2hpbmcvdjFiZXRhMS90eC5wcm90bxIXY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEilAEKCU1zZ1VuamFpbBJVCg52YWxpZGF0b3JfYWRkchgBIAEoCUI96t4fB2FkZHJlc3PStC0dY29zbW9zLlZhbGlkYXRvckFkZHJlc3NTdHJpbmei57AqB2FkZHJlc3Oo57AqATowiKAfAILnsCoOdmFsaWRhdG9yX2FkZHKK57AqFGNvc21vcy1zZGsvTXNnVW5qYWlsIhMKEU1zZ1VuamFpbFJlc3BvbnNlIrQBCg9Nc2dVcGRhdGVQYXJhbXMSKwoJYXV0aG9yaXR5GAEgASgJQhjStC0UY29zbW9zLkFkZHJlc3NTdHJpbmcSOgoGcGFyYW1zGAIgASgLMh8uY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEuUGFyYW1zQgnI3h8AqOewKgE6OILnsCoJYXV0aG9yaXR5iuewKiVjb3Ntb3Mtc2RrL3gvc2xhc2hpbmcvTXNnVXBkYXRlUGFyYW1zIhkKF01zZ1VwZGF0ZVBhcmFtc1Jlc3BvbnNlMtIBCgNNc2cSWAoGVW5qYWlsEiIuY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEuTXNnVW5qYWlsGiouY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEuTXNnVW5qYWlsUmVzcG9uc2USagoMVXBkYXRlUGFyYW1zEiguY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEuTXNnVXBkYXRlUGFyYW1zGjAuY29zbW9zLnNsYXNoaW5nLnYxYmV0YTEuTXNnVXBkYXRlUGFyYW1zUmVzcG9uc2UaBYDnsCoBQjNaLWdpdGh1Yi5jb20vY29zbW9zL2Nvc21vcy1zZGsveC9zbGFzaGluZy90eXBlc6jiHgFiBnByb3RvMw", [file_gogoproto_gogo, file_cosmos_slashing_v1beta1_slashing, file_cosmos_proto_cosmos, file_cosmos_msg_v1_msg, file_amino_amino]);

/**
 * MsgUnjail defines the Msg/Unjail request type
 *
 * @generated from message cosmos.slashing.v1beta1.MsgUnjail
 */
export type MsgUnjail = Message<"cosmos.slashing.v1beta1.MsgUnjail"> & {
  /**
   * @generated from field: string validator_addr = 1;
   */
  validatorAddr: string;
};

/**
 * Describes the message cosmos.slashing.v1beta1.MsgUnjail.
 * Use `create(MsgUnjailSchema)` to create a new message.
 */
export const MsgUnjailSchema: GenMessage<MsgUnjail> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_tx, 0);

/**
 * MsgUnjailResponse defines the Msg/Unjail response type
 *
 * @generated from message cosmos.slashing.v1beta1.MsgUnjailResponse
 */
export type MsgUnjailResponse = Message<"cosmos.slashing.v1beta1.MsgUnjailResponse"> & {
};

/**
 * Describes the message cosmos.slashing.v1beta1.MsgUnjailResponse.
 * Use `create(MsgUnjailResponseSchema)` to create a new message.
 */
export const MsgUnjailResponseSchema: GenMessage<MsgUnjailResponse> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_tx, 1);

/**
 * MsgUpdateParams is the Msg/UpdateParams request type.
 *
 * Since: cosmos-sdk 0.47
 *
 * @generated from message cosmos.slashing.v1beta1.MsgUpdateParams
 */
export type MsgUpdateParams = Message<"cosmos.slashing.v1beta1.MsgUpdateParams"> & {
  /**
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   *
   * @generated from field: string authority = 1;
   */
  authority: string;

  /**
   * params defines the x/slashing parameters to update.
   *
   * NOTE: All parameters must be supplied.
   *
   * @generated from field: cosmos.slashing.v1beta1.Params params = 2;
   */
  params?: Params;
};

/**
 * Describes the message cosmos.slashing.v1beta1.MsgUpdateParams.
 * Use `create(MsgUpdateParamsSchema)` to create a new message.
 */
export const MsgUpdateParamsSchema: GenMessage<MsgUpdateParams> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_tx, 2);

/**
 * MsgUpdateParamsResponse defines the response structure for executing a
 * MsgUpdateParams message.
 *
 * Since: cosmos-sdk 0.47
 *
 * @generated from message cosmos.slashing.v1beta1.MsgUpdateParamsResponse
 */
export type MsgUpdateParamsResponse = Message<"cosmos.slashing.v1beta1.MsgUpdateParamsResponse"> & {
};

/**
 * Describes the message cosmos.slashing.v1beta1.MsgUpdateParamsResponse.
 * Use `create(MsgUpdateParamsResponseSchema)` to create a new message.
 */
export const MsgUpdateParamsResponseSchema: GenMessage<MsgUpdateParamsResponse> = /*@__PURE__*/
  messageDesc(file_cosmos_slashing_v1beta1_tx, 3);

/**
 * Msg defines the slashing Msg service.
 *
 * @generated from service cosmos.slashing.v1beta1.Msg
 */
export const Msg: GenService<{
  /**
   * Unjail defines a method for unjailing a jailed validator, thus returning
   * them into the bonded validator set, so they can begin receiving provisions
   * and rewards again.
   *
   * @generated from rpc cosmos.slashing.v1beta1.Msg.Unjail
   */
  unjail: {
    methodKind: "unary";
    input: typeof MsgUnjailSchema;
    output: typeof MsgUnjailResponseSchema;
  },
  /**
   * UpdateParams defines a governance operation for updating the x/slashing module
   * parameters. The authority defaults to the x/gov module account.
   *
   * Since: cosmos-sdk 0.47
   *
   * @generated from rpc cosmos.slashing.v1beta1.Msg.UpdateParams
   */
  updateParams: {
    methodKind: "unary";
    input: typeof MsgUpdateParamsSchema;
    output: typeof MsgUpdateParamsResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_cosmos_slashing_v1beta1_tx, 0);

